### ISSUE TITLE
Build for Scala 2.13.0

### ISSUE THREAD

**Issue by Atry** [ThoughtWorksInc/Binding.scala#175]
- [x] Scala
- [x] Scala.js
- [x] Scalaz
- [x] ScalaTest - https://github.com/scalatest/scalatest/issues/1601
- [x] sde - https://github.com/ThoughtWorksInc/sde/issues/11
- [x] Extractor.scala - https://github.com/ThoughtWorksInc/Extractor.scala/pull/19
- [x] Q.scala - https://github.com/ThoughtWorksInc/Q.scala/pull/3
- [x] ScalaTags - https://repo1.maven.org/maven2/com/lihaoyi/scalatags_2.13/
- [x] Reimplement `SafeBuffer` for Scala 2.13 collections
- [x] Reimplement `Proxy` for Scala 2.13 collections

**Comment by Atry** [comment]
An working in process branch for Scala 2.13:
https://github.com/Atry/Binding.scala/tree/scala-2.13-wip

**Comment by adrobisch** [comment]
Hi, would be nice to see a 2.13 release. Is there a way to help out on this one?

**Comment by Atry** [comment]
You can try to checkout https://github.com/Atry/Binding.scala/tree/scala-2.13-wip and fix compilation errors. You may need to add some [@enableMembersIf](https://github.com/ThoughtWorksInc/enableIf.scala) annotation for Scala 2.13 only code.

**Comment by adrobisch** [comment]
I did a `sbt test` after adding some openjfx dependencies and only one error appeared: 
```
fxml/.jvm/src/test/scala/com/thoughtworks/binding/FxmlSample.scala:19:8: ambiguous implicit values:
[error]  both method javaBeanTyper in trait LowPriorityBuilder of type [A](implicit constructor: com.thoughtworks.binding.fxml.Runtime.EmptyConstructor[A])com.thoughtworks.binding.fxml.Runtime.JavaBeanPropertyTyper[A]
[error]  and macro method javafxTyper in object PropertyTyper of type [A]=> com.thoughtworks.binding.fxml.Runtime.PropertyTyper[A]
[error]  match expected type com.thoughtworks.binding.fxml.Runtime.PropertyTyper[javafx.stage.Stage]
[error]       <Stage title={text}>
[error]   
```
All other tests are green. Am I missing something?

**Comment by Atry** [comment]
There should be more compilation error. See https://travis-ci.org/Atry/Binding.scala/builds/548268187

**Comment by adrobisch** [comment]
Sorry did not run a cross build, will take a look.

**Comment by adrobisch** [comment]
Invested a bit of time here: https://github.com/ThoughtWorksInc/Binding.scala/compare/master...adrobisch:scala-2.13-wip 
I fixed all the library versions to my best knowledge and migrated `SafeBuffer` to 2.13. In `Binding.scala` however the collection changes are a bit more complicated. I worked on migrating `Proxy` which should work out but is WIP. `HasCache` however is having issues with Scala.js interfaces which are still like 2.12 as far as I understand the compiler errors, which looks like it needs bigger changes.

**Comment by Atry** [comment]
I think we should implement `Proxy` as a `SeqView` instead of a `Seq` in Scala 2.13, also the type of `BindingSeq.value` should be `SeqOps` instead of a `Seq`.

**Comment by adrobisch** [comment]
Its pretty hard for me to work on the codebase with all the versioning and target (mostly Scala.js) implications. I also dont feel comfortable doing the proposed changes given my current level of understanding, so I will not follow-up on this at the moment. Feel free to pick whatever you like from my branch.

**Comment by Atry** [comment]
I know it's really hard to keep the ability of cross compilation when there are plenty of API changes in standard library. Thanks for your attempting implementation!

**Comment by Atry** [comment]
Since the collection API changes in Scala 2.13, it is impossible to support Scala 2.13 without breaking backward-compatibility.
