### ISSUE TITLE
Object FutureBinding is not a member of package com.thoughtworks.binding @v9.0.1

### ISSUE THREAD

**Issue by andwxh** [ThoughtWorksInc/Binding.scala#8]
I'm trying to use **_FutureBinding_** with this build config:
```
libraryDependencies += "com.thoughtworks.binding" %%% "futurebinding" % "latest.release"
libraryDependencies += "com.thoughtworks.binding" %%% "dom" % "latest.release"
enablePlugins(ScalaJSPlugin)
addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full)
```
At this point **_latest.release_** resolved to the version **9.0.1**.

And compiler report the following when compiling:
```
[error] ....../component/ConnectDialog.scala:4: object FutureBinding is not a member of package com.thoughtworks.binding
[error] import com.thoughtworks.binding.FutureBinding
[error]        ^
[error] ....../component/ConnectDialog.scala:36: not found: value FutureBinding
[error]       {val result = FutureBinding(Ajax.get(s"mock/2"))
[error]                           ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed 2016-9-20 15:36:30
```

I have checked the **_Binding.scala-website_** project finding out it was compiling with version 8.0.0.

Then I was tried to switch version to 8.0.0 & 9.0.0, both of these versions works well.

Is there something changed at version 9.0.1?

**Comment by Atry** [comment]
See https://github.com/ThoughtWorksInc/Binding.scala/releases/tag/v8.0.0 and https://github.com/ThoughtWorksInc/Binding.scala#remote-data-binding-for-scalaconcurrentfuture-futurebindingscala

The `FutureBinding` class has been moved to a separate library.

**Comment by andwxh** [comment]
Thank you for your reply.

But I'm using the separated library "futurebinding" for sure.

And I have checked the release note of version 9.0.1, and it not mentioned anything changed about the packaging.

**Comment by Atry** [comment]
I upgrade `Binding.scala-website` to 9.0.1, it compiles: https://travis-ci.org/ThoughtWorksInc/Binding.scala-website/builds/161263999

**Comment by andwxh** [comment]
Yes, it compiles on my laptop too.

I'm trying to figure out what happened to my project.

**Comment by andwxh** [comment]
I cannot reproduce this case now. My project can compile with version 9.0.1 for now.

When I trying to switch the version, I have once removed the entire **_target_** folder. I guess that there is something temporally goes wrong in there. But because the **_target_** folder is removed, I cannot verify it anymore.

Thank you for upgrading the build config of **_Binding.scala-website_**.

I should switch back to v9.0.1 again before I post this issue, sorry for the unreproducible issue.

**Comment by Atry** [comment]
Never mind.

Have fun!
